---

name: 'Test deploy-to-s3-bucket action'
description: 'Runs validation agains the deploy-to-s3-bucket action'

inputs:
  aws-account-id:
    description: 'The AWS Account id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install BATS and jq'
      shell: bash
      run: |
        # Add brews to the path
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        # Setup brew environment
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        # Install bats
        brew install bats-core jq

    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Use local actions'
      uses: ./.github/actions/use-local-actions

    - name: 'Get unique id'
      id: id
      shell: bash
      run: echo "::set-output name=id::$(date '+%s')"

    - name: 'Create archive file'
      shell: bash
      run: tar -zcvf archive.tgz -C ${{ github.action_path }}/assets .

    - name: 'Run deploy-to-s3-bucket action'
      id: unpack
      uses: ./actions/deploy-to-s3-bucket
      with:
        pattern: 'archive.tgz'
        s3-bucket: shopsmart-github-actions-tests
        s3-bucket-path: ${{ steps.id.outputs.id }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests-s3

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: 'us-east-1'
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests-s3

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/deploy-to-s3-bucket.bats
      env:
        S3_BUCKET: shopsmart-github-actions-tests
        S3_BUCKET_PATH: ${{ steps.id.outputs.id }}
