---

name: 'Test setup-brew'
description: 'Runs validation against the setup-brew action'

runs:
  using: 'composite'
  steps:
    - name: 'Install BATS'
      shell: bash
      run: |
        # Add brews to the path
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        # Setup brew environment
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        # Install bats
        brew install bats-core

    - name: 'Checkout actions'
      uses: actions/checkout@v2

    - name: 'Create a Brewfile'
      shell: bash
      run: |
        {
          echo "brew 'go'"
          echo "brew 'the_silver_searcher'"
        } > Brewfile

    - name: 'Run setup-brew action'
      uses: ./actions/setup-brew

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/setup-brew.bats
