---
repository:
  name: github-actouns
  description: |
    Wraps Github Actions into composite actions and workflows for
    easier reusability within the organization.
  private: false
  has_issues: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

teams:
  - name: tech-ops-team
    permission: admin
  - name: developers
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: false
        contexts:
          - Pre-commit check
          - Run tests
      enforce_admins: false
      required_linear_history: true
      restrictions:
        users: []
        teams: []
        apps: []
