---

repos:
  # Put this first because the dist gets a few violations for the following hooks
  - repo: local
    hooks:
      - id: build-create-datadog-downtime-dist
        name: Build the create-datadog-downtime dist
        entry: bash -c 'cd actions/create-datadog-downtime && npm run build'
        language: system
        verbose: true
        files: ^actions/create-datadog-downtime/(src\/.*\.ts|jest\.config\.js|tsconfig\.json|package(-lock)?\.json)$
        pass_filenames: false

  ## General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^.*/dist/.*$
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
      - id: trailing-whitespace
        exclude: ^.*/dist/.*$
