---

repos:
  ## General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
      - id: trailing-whitespace

  ## Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_docs
        always_run: true
      - id: terraform_fmt
      - id: terraform_tflint
        alias: terraform_tflint_nocreds
        name: terraform_tflint_nocreds
      - id: terraform_tfsec
  - repo: local
    hooks:
      - id: terraform_validate
        name: terraform_validate
        entry: |
          bash -c '
            cd terraform
            export AWS_DEFAULT_REGION=us-east-1
            declare -a DIRS
            for FILE in "$@"
            do
              DIRS+=($(dirname "$FILE"))
            done
            for DIR in $(printf "%s\n" "${DIRS[@]}" | sort -u)
            do
              cd $(dirname "$FILE")
              terraform init -backend=false -input=false
              terraform validate .
            done
          '
        language: system
        verbose: true
        files: \.tf(vars)?$
