---

name: 'Test setup-node'
description: 'Runs validation agains the setup-node action'

runs:
  using: 'composite'
  steps:
    - name: 'Install BATS'
      shell: bash
      run: |
        # Add brews to the path
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        # Setup brew environment
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        # Install bats
        brew install bats-core

    - name: 'Checkout actions'
      uses: actions/checkout@v2

    - name: 'Checkout hello world project'
      uses: actions/checkout@v2
      with:
        repository: mike-carey/hello-world-nodejs
        path: ./hello-world

    - name: 'Run setup-node action'
      id: setup
      uses: ./actions/setup-node
      with:
        node-version: '14'
        working-directory: ./hello-world

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/setup-node.bats
      env:
        DIRECTORY: ./hello-world
        NODE_VERSION: ${{ steps.setup.outputs.node-version }}
