---

name: 'Test unpack-archive action'
description: 'Runs validation agains the unpack-archive action'

runs:
  using: 'composite'
  steps:
    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Create archive file'
      run: tar -zxvf archive.tgz -C $GITHUB_ACTION_PATH/assets .

    - name: 'Run unpack-archive action'
      id: unpack
      uses: ./actions/unpack-archive
      with:
        filename: 'archive.tgz'

    - name: 'Validate'
      shell: bash
      run: bats -r $GITHUB_ACTION_PATH/unpack-archive.bats
      env:
        DESTINATION: ${{ steps.unpack.outputs.destination }}
        MIME_TYPE: ${{ steps.unpack.outputs.mime-type }}
