---

name: 'Test setup-homebrew'
description: 'Runs validation against the setup-homebrew action'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Homebrew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout actions'
      uses: actions/checkout@v4

    - name: 'Create a Brewfile'
      shell: bash
      run: |
        {
          echo "brew 'tflint'"
          echo "brew 'the_silver_searcher'"
        } > Brewfile

    - name: 'Run setup-brew action'
      uses: ./actions/setup-homebrew

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/setup-homebrew.bats
