---

name: 'Test render-task-definition workflow'
description: 'Runs validation against the render-task-definition workflow'

inputs:
  ref:
    description: 'The github ref to expect'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup brew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Download task-definition'
      uses: actions/download-artifact@v3
      with:
        name: task-definition-renamed

    - name: 'Validate'
      shell: bash
      run: bats --verbose-run -r ${{ github.action_path }}/render-task-definition.bats
      env:
        VERSION_TAG: ${{ inputs.ref || github.sha }}
