---

name: 'Notify slack'
description: 'Posts a slack message with the status of the pipeline'

inputs:
  application:
    description: 'The friendly name for the application'
    type: string
    required: true
  data:
    description: 'The path to the file with data to pass to the render'
    type: string
    required: false
    default: ''
  emoji:
    description: 'The github release emoji to display'
    default: ''
  environment:
    description: |
      The environment variables to pass to the render.  Each environment variable should be in format VAR=VAL with one on each line.
      Example:
        environment: |
          FOO=bar
          BAR=baz
    type: string
    required: false
    default: ''
  format:
    description: 'The format the data file will be in'
    type: string
    required: false
    default: ''
  version:
    description: 'The version that is being deployed'
    type: string
    default: ${{ github.ref }}
  type:
    description: 'The type of action that is being performed such as build or deployment'
    type: string
    required: true
  template:
    description: 'The path to the template file to render'
    type: string
    required: true
  status:
    description: 'The status of the deployment.  Options are started, success, and failure'
    type: string
    required: true
  slack-webhook-url:
    description: 'The slack webhook url to post the message to'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Run timestamp'
      id: timestamp
      run: |
        TIMESTAMP="$(date +%s)"
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
      shell: bash

    - name: 'Render payload'
      id: render
      uses: shopsmart/render-j2-action@v1
      with:
        template: .github/actions/test-notify-slack/message.json.j2
        format: json
        env_vars: |
          APPLICATION=${{ inputs.application }}
          ENVIRONMENT=${{ inputs.environment }}
          EMOJI=${{ inputs.emoji }}
          VERSION=${{ inputs.version }}
          TYPE=${{ inputs.type }}
          STATUS=${{ inputs.status }}
          ACTOR=${{ github.actor }}
          RUN_ID=${{ github.run_id }}
          REPOSITORY=${{ github.repository }}
          TEMPLATE=${{ inputs.template }}
          REF=${{ github.ref_name }}
          TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}

    - name: 'Post message to slack'
      id: slack
      uses: slackapi/slack-github-action@v1
      with:
        payload: ${{ steps.render.outputs.content }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
