---

name: 'Test deploy-to-lambda-function action'
description: 'Runs validation against the deploy-to-lambda-function action'

inputs:
  aws-account-id:
    description: 'The AWS Account id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup brew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Use local actions'
      uses: ./.github/actions/use-local-actions

    - name: 'Create archive file'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        sed -i "s/const VERSION = 'dev'/const VERSION = '${{ github.sha }}'/" index.js
        tar -czvf archive.tgz ./index.js

    - name: 'Run deploy-lambda-function action'
      id: unpack
      uses: ./actions/deploy-lambda-function
      with:
        pattern: ${{ github.action_path }}/archive.tgz
        function-name: shopsmart-github-actions-tests
        function-tags: version=${{ github.sha }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests-lambda

    # TODO: Is this needed?
    # - name: 'Configure AWS Credentials'
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: 'us-east-1'
    #     role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests-lambda

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/deploy-lambda-function.bats
      env:
        FUNCTION_ARN: arn:aws:lambda:us-east-1:${{ inputs.aws-account-id }}:function:shopsmart-github-actions-test
        # FUNCTION_NAME: shopsmart-github-actions-tests
        VERSION_TAG: ${{ github.sha }}
