---

name: 'Test deploy-to-lambda-function action'
description: 'Runs validation against the deploy-to-lambda-function action'

inputs:
  aws-account-id:
    description: 'The AWS Account id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup brew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Use local actions'
      uses: ./.github/actions/use-local-actions

    - name: 'Create archive file'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        sed -i "s/const VERSION = 'dev'/const VERSION = '${{ github.sha }}'/" index.js
        zip archive.zip ./index.js

    - name: 'Run deploy-lambda-function action'
      id: unpack
      uses: ./actions/deploy-lambda-function
      with:
        pattern: ${{ github.action_path }}/archive.zip
        function-name: shopsmart-github-actions-tests
        function-tags: version=${{ github.sha }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests
        s3-bucket: shopsmart-github-actions-tests
        s3-key: lambda-artifacts/${{ github.sha }}/function.zip
        s3-tags: version=${{ github.sha }}
        current-version-file: lambda-artifacts/current-version

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: 'us-east-1'
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/deploy-lambda-function.bats
      env:
        S3_BUCKET: shopsmart-github-actions-tests
        S3_KEY: lambda-artifacts/${{ github.sha }}/function.zip
        FUNCTION_ARN: arn:aws:lambda:us-east-1:${{ inputs.aws-account-id }}:function:shopsmart-github-actions-tests
        VERSION_TAG: ${{ github.sha }}
