---

name: 'Deploy lambda function'
description: 'Deploys a lambda function'

inputs:
  zip-file:
    description: The path to the zip file to upload as the new lambda function code.
    required: true

  # Lambda options
  function-name:
    description: The name of the function name
    required: true
  function-tags:
    description: |
      Key value pairs to attach to the lambda function

      Example:
        function-tags: |
          version=v1
          owner=carl
    default: ''
  publish-version:
    description: If true, a lambda version will be published
    default: 'true'

  # s3 options
  upload-to-s3:
    description: If true and an s3-bucket is provided, the action will upload the asset to s3 before updating the lambda
    default: 'true'
  s3-bucket:
    description: The s3 bucket to upload the artifact to
    default: ''
  s3-key:
    description: The path within the s3 bucket to upload the artifact to
    default: ''
  s3-tags:
    description: |
      Key value pairs to attach to the s3 object

      Example:
        s3-tags: |
          version=v1
          owner=carl
    default: ''

outputs:
  version:
    description: The version of the lambda that was published (if publish-version is true)
    value: ${{ steps.publish-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 'Upload lambda code'
      uses: shopsmart/github-actions/actions/deploy-to-s3-bucket@bugfix/s3-tags
      if: inputs.s3-bucket != '' && inputs.upload-to-s3 == 'true'
      with:
        pattern: ${{ inputs.zip-file }}
        unpack: false
        s3-bucket: ${{ inputs.s3-bucket }}
        s3-bucket-path: ${{ inputs.s3-key }}
        s3-tags: ${{ inputs.s3-tags }}

    - name: 'Deploy lambda code'
      shell: bash
      run: ${{ github.action_path }}/deploy-lambda.sh "${{ inputs.function-name }}" "${{ inputs.zip-file }}"
      env:
        S3_BUCKET: ${{ inputs.s3-bucket }}
        S3_KEY: ${{ inputs.s3-key }}

    - name: 'Tag the lambda'
      shell: bash
      run: ${{ github.action_path }}/tag-lambda.sh "${{ inputs.function-name }}"
      env:
        LAMBDA_TAGS: ${{ inputs.function-tags }}
      if: inputs.function-tags != ''

    - name: 'Cut a version of the lambda'
      id: publish-version
      if: inputs.publish-version == 'true'
      shell: bash
      run: ${{ github.action_path }}/version-lambda.sh "${{ inputs.function-name }}" "${{ inputs.tag || github.sha }}"
