---

name: 'Test notify slack action'
description: 'Runs validation against the notify-slack action'

runs:
  using: "composite"
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Post message to slack'
      id: slack
      uses: ./actions/notify-slack
      with:
        application: github-actions
        environment: staging
        status: ${{ inputs.status }}
        type: test
        version: v1.0.56
        template: ${{ inputs.template }}
        slack-webhook-url: ${{ inputs.slack-webhook-url }}
