---

name: 'Test build-ecr-image workflow'
description: 'Runs validation against the build-ecr-image workflow'

inputs:
  aws-account-id:
    description: 'The AWS Account id'
    required: true
  ref:
    description: 'The github ref to expect'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup brew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: 'us-east-1'
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-tests

    - name: 'Log into AWS ECR'
      uses: aws-actions/amazon-ecr-login@v2

    - name: 'Validate'
      shell: bash
      run: bats --verbose-run -r ${{ github.action_path }}/build-ecr-image.bats
      env:
        ECR_REPOSITORY: ${{ inputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/github-actions-tests
        VERSION_TAG: ${{ inputs.ref }}
