---

name: 'Deploy to s3 bucket'
description: 'Deploys assets to an s3 bucket'

inputs:
  pattern:
    description: |
      If downloading release assets from github, the pattern for the assets file.
      Otherwise, the path to the assets.  If it is an archive, it will unpacked.
    required: true

  # GH release Options
  github-token:
    description: 'The github token to allow for searching for release assets'
    type: string
    default: ${{ github.token }}
  tag:
    description: 'The github release tag to pull that assets from'
    default: ''

  # AWS (S3) Options
  aws-access-key-id:
    description: 'The AWS access key id to log into ECR with'
    default: ''
  aws-secret-access-key:
    description: 'The AWS secret access key to log into ECR with'
    default: ''
  aws-region:
    description: 'The AWS region to log into if using ECR'
    default: 'us-east-1'
  role-to-assume:
    description: 'Allows one to configure the assume role'
    default: ''
  role-duration-seconds:
    description: 'Allows one to configure the duration of assume role'
    default: 1200

  s3-bucket:
    description: 'The name of the s3 bucket to upload the assets to'
    required: true
  s3-bucket-path:
    description: 'The path within the s3 bucket to upload the assets to'
    default: ''
  s3-tags:
    description: |
      Key value pairs to attach to each s3 object.

      Example:
        s3-tags: |
          version=v1
          owner=carl
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Download release assets'
      shell: bash
      run: gh -R "${{ github.repository }}" release download -p "${{ inputs.pattern }}" "${{ inputs.tag }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      # Only if we are downloading assets from gh release
      if: inputs.tag != ''

    - name: 'Unpack assets'
      id: unpack
      uses: shopsmart/github-actions/actions/unpack-archive@v2
      with:
        filename: ${{ inputs.pattern }}
        destination: assets

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}

    - name: 'Upload assets'
      shell: bash
      run: ${{ github.action_path }}/upload-assets.sh "${{ steps.unpack.outputs.destination }}"
      env:
        S3_BUCKET: ${{ inputs.s3-bucket }}
        S3_BUCKET_PATH: ${{ inputs.s3-bucket-path }}

    - name: 'Tag assets'
      shell: bash
      run: ${{ github.action_path }}/tag-assets.sh "${{ steps.unpack.outputs.destination }}"
      env:
        S3_BUCKET: ${{ inputs.s3-bucket }}
        S3_BUCKET_PATH: ${{ inputs.s3-bucket-path }}
        S3_TAGS: ${{ inputs.s3-tags }}
      if: inputs.s3-tags != ''
