---

name: 'Test package-archive action'
description: 'Runs validation agains the package-archive action'

runs:
  using: 'composite'
  steps:
    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Run package-archive action'
      id: unpack
      uses: ./actions/package-archive
      with:
        directory: $GITHUB_ACTION_PATH/assets

    - name: 'Validate'
      shell: bash
      run: bats -r $GITHUB_ACTION_PATH/package-archive.bats
      env:
        FILENAME: ${{ steps.unpack.outputs.filename }}
