---

name: 'Test is-gh-release action'
description: 'Runs validation against the is-gh-release action'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Homebrew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Install BATS'
      shell: bash
      run: brew install bats-core

    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Use local actions'
      uses: ./.github/actions/use-local-actions

    # Empty string
    - name: 'Empty string: Is GH release?'
      id: empty_string
      uses: ./actions/is-gh-release

    # nothere
    - name: 'nothere: Is GH release?'
      id: nothere
      uses: ./actions/is-gh-release
      with:
        ref: nothere

    # v2.0.2
    - name: 'v2.0.2: Is GH release?'
      id: v2_0_2
      uses: ./actions/is-gh-release
      with:
        ref: v2.0.2

    # cli/cli v2.3.0
    - name: 'cli/cli v2.3.0: Is GH release?'
      id: cli_cli_v2_3_0
      uses: ./actions/is-gh-release
      with:
        ref: v2.3.0
        repository: cli/cli

    - name: 'Validate'
      shell: bash
      run: bats -r ${{ github.action_path }}/is-gh-release.bats
      env:
        EMPTY_STRING_IS_RELEASE: ${{ steps.empty_string.outputs.is-release }}
        NOTHERE_IS_RELEASE: ${{ steps.nothere.outputs.is-release }}
        V2_0_2_IS_RELEASE: ${{ steps.v2_0_2.outputs.is-release }}
        CLI_CLI_V2_3_0_IS_RELEASE: ${{ steps.cli_cli_v2_3_0.outputs.is-release }}
