###
# This test of the action is very limited.  If anything, this tests
# that the action is not invalid; however, it does not test any of
# the functionality of downloading release assets or uploading to s3
# bucket without aws credentials.
##
---

name: 'Run deploy-static-assets action'

on:
  pull_request:
    paths:
      - actions/deploy-static-assets/*
      - actions/unpack-archive/*

defaults:
  run:
    shell: bash

jobs:
  test-deploy-static-assets-action:
    name: 'Uses the deploy-static-assets action'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout actions'
        uses: actions/checkout@v2

      - name: 'Use local actions'
        uses: ./.github/actions/use-local-actions

      - name: 'Debug'
        run: cat actions/deploy-static-assets/action.yml

      - name: 'Create dummy files'
        run: |
          mkdir -p static-assets
          echo "<html><head></head><body>Hello world</body></html>" > static-assets/index.html
          echo "head p { color: black; }" > static-assets/style.css
          tar -zcvf static-assets.tgz -C static-assets/ .
          rm -rf static-assets/

      - name: 'Run deploy static assets'
        uses: ./actions/deploy-static-assets
        with:
          pattern: 'static-assets.tgz'
